const path=require('path');const http=require('http');const express=require('express');const {Server}=require('socket.io');
const app=express();const server=http.createServer(app);const io=new Server(server);const rooms=new Map();
const words=['APPLE','ROCKET','BANANA','TIGER','OCEAN','PIZZA','GUITAR','CASTLE','SUNSET','THUNDER','COFFEE','DRAGON','PLANET','COOKIE','BASKET','JUNGLE','RAINBOW','PENGUIN','MOUNTAIN','POPCORN'];
function code(){let c;do{c=Math.random().toString(36).slice(2,6).toUpperCase()}while(rooms.has(c));return c}
function state(r){return {players:[...r.players.values()].map(p=>({id:p.id,name:p.name})),hostId:r.hostId,scores:Object.fromEntries([...r.players].map(([id,p])=>[id,p.score])),status:r.status}}
function emitState(r){io.to(r.code).emit('roomState',state(r))}
function begin(r){r.status='game';r.round=0;r.used=[];for(const p of r.players.values())p.score=0;nextWord(r)}
function nextWord(r){if(r.round>=r.total)return finish(r);r.round++;r.word=words[Math.floor(Math.random()*words.length)];r.startedAt=Date.now();r.answered=new Set();r.timeLimit=5;io.to(r.code).emit('gameStarted',{word:r.word,round:r.round,total:r.total,timeLimit:r.timeLimit});clearInterval(r.timer);r.timer=setInterval(()=>{const left=Math.max(0,r.timeLimit-Math.floor((Date.now()-r.startedAt)/1000));io.to(r.code).emit('tick',left);if(left<=0){clearInterval(r.timer);setTimeout(()=>nextWord(r),400)}},250)}
function finish(r){clearInterval(r.timer);r.status='results';const results=[...r.players.values()].sort((a,b)=>b.score-a.score).map(p=>({id:p.id,name:p.name,score:p.score}));const top=results[0];io.to(r.code).emit('roundResult',{winner:top,results,scores:Object.fromEntries(results.map(p=>[p.id,p.score]))})}
io.on('connection',socket=>{
 socket.on('createRoom',({name})=>{const c=code();const r={code:c,hostId:socket.id,players:new Map(),status:'lobby',round:0,total:10,word:'',timer:null};r.players.set(socket.id,{id:socket.id,name:String(name).slice(0,16),score:0});rooms.set(c,r);socket.join(c);socket.roomCode=c;socket.emit('roomCreated',{code:c,hostId:socket.id});emitState(r)});
 socket.on('joinRoom',({name,code})=>{const r=rooms.get(String(code).toUpperCase());if(!r)return socket.emit('errorMessage','Room not found.');if(r.status!=='lobby'&&r.status!=='results')return socket.emit('errorMessage','That game is already in progress.');if(r.players.size>=8)return socket.emit('errorMessage','Room is full.');r.players.set(socket.id,{id:socket.id,name:String(name).slice(0,16),score:0});socket.join(r.code);socket.roomCode=r.code;emitState(r)});
 socket.on('startGame',()=>{const r=rooms.get(socket.roomCode);if(!r||r.hostId!==socket.id)return;if(r.players.size)begin(r)});
 socket.on('submitAnswer',({answer})=>{const r=rooms.get(socket.roomCode);if(!r||r.status!=='game'||r.answered.has(socket.id))return;if(Date.now()-r.startedAt>r.timeLimit*1000)return;if(String(answer).trim().toUpperCase()!==r.word)return socket.emit('answerResult',{message:'Not quite — try again!'});r.answered.add(socket.id);const p=r.players.get(socket.id);const rank=r.answered.size;const points=[100,75,50,25][rank-1]||25;const elapsed=(Date.now()-r.startedAt)/1000;const bonus=Math.max(0,Math.round((r.timeLimit-elapsed)*10));p.score+=points+bonus;socket.emit('answerResult',{message:`✓ Correct! +${points+bonus} points`});io.to(r.code).emit('scoreUpdate',{scores:Object.fromEntries([...r.players].map(([id,x])=>[id,x.score]))});if(r.answered.size===r.players.size){clearInterval(r.timer);setTimeout(()=>nextWord(r),700)}});
 socket.on('playAgain',()=>{const r=rooms.get(socket.roomCode);if(!r||r.hostId!==socket.id)return;begin(r)});
 socket.on('disconnect',()=>{const c=socket.roomCode,r=rooms.get(c);if(!r)return;r.players.delete(socket.id);if(r.hostId===socket.id){const next=r.players.values().next().value;if(next)r.hostId=next.id;else{clearInterval(r.timer);rooms.delete(c);return}}emitState(r)})
});
const dist=path.join(__dirname,'..','dist');app.use(express.static(dist));app.get('/*splat', (req, res) =>res.sendFile(path.join(dist,'index.html')));
const PORT=process.env.PORT||3000;server.listen(PORT,()=>console.log(`Word Rush running on ${PORT}`));
